var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
import * as React from 'react';
import './style-pc.less';
var Onrecord_PC = /** @class */ (function (_super) {
    __extends(Onrecord_PC, _super);
    function Onrecord_PC() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Onrecord_PC.prototype.render = function () {
        return (React.createElement("div", { id: "onrecord-pc", className: "page-pc" },
            React.createElement("ul", { className: "onrecord-menu" },
                React.createElement("li", { className: "onrecord big-block" },
                    React.createElement("p", { className: "title" }, "\u5907\u6848\u4FE1\u606F"),
                    React.createElement("ul", { className: "schedule" },
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u7EC6\u5219\u51FA\u53F0")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u51C6\u5907\u8D44\u6599")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao2" }),
                                React.createElement("div", { className: "step-desc" }, "\u63D0\u4EA4\u8D44\u6599")),
                            React.createElement("div", { className: "line gray" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-shuzi4" }),
                                React.createElement("div", { className: "step-desc gray" }, "\u7B49\u5F85\u5BA1\u6838")),
                            React.createElement("div", { className: "line gray" })),
                        React.createElement("li", { className: "block last" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-shuzi5" }),
                                React.createElement("div", { className: "step-desc gray" }, "\u5907\u6848\u767B\u8BB0"))))),
                React.createElement("li", { className: "dianxin big-block" },
                    React.createElement("p", { className: "title" }, "\u589E\u503C\u7535\u4FE1\u4E1A\u52A1\u7ECF\u8425\u8BB8\u53EF\u8BC1\u4FE1\u606F"),
                    React.createElement("ul", { className: "schedule" },
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u63D0\u4EA4\u8D44\u6599")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u7B49\u5F85\u5BA1\u6838")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block last" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u9886\u53D6\u8BC1\u4E66"))))),
                React.createElement("li", { className: "money big-block" },
                    React.createElement("p", { className: "title" }, "\u8D44\u91D1\u5B58\u7BA1\u4FE1\u606F"),
                    React.createElement("ul", { className: "schedule" },
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    "\u53EF\u5B58\u7BA1\u94F6",
                                    React.createElement("br", null),
                                    "\u884C\u8C03\u67E5")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    React.createElement("div", { className: "communication step-desc" }, "\u94F6\u884C\u5BF9\u63A5\u6C9F\u901A"))),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u7B5B\u9009\u94F6\u884C")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    "\u8D44\u6599\u5BF9\u63A5",
                                    React.createElement("br", null),
                                    React.createElement("p", { className: "bank gray" }, "\u6D77\u53E3\u8054\u5408\u519C\u5546\u94F6\u884C"))),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    "\u7B7E\u7F72\u534F\u8BAE",
                                    React.createElement("br", null),
                                    React.createElement("p", { className: "gray date" }, "2017-3-3"))),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u6280\u672F\u7814\u53D1")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" }, "\u5F00\u53D1\u6D4B\u8BD5")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block last" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    "\u5B8C\u6210\u4E0A\u7EBF",
                                    React.createElement("br", null),
                                    React.createElement("p", { className: "gray date" }, "2017-3-3")))))),
                React.createElement("li", { className: "security big-block" },
                    React.createElement("p", { className: "title" }, "\u4FE1\u606F\u5B89\u5168\u6D4B\u8BC4\u8BA4\u8BC1\u4FE1\u606F"),
                    React.createElement("ul", { className: "schedule" },
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    "\u501F\u8D37\u4E1A\u52A1",
                                    React.createElement("br", null),
                                    "\u6570\u636E\u4FDD\u5B58")),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    React.createElement("p", { className: "save step-desc" }, "\u4E0A\u7F51\u65E5\u5FD7\u4FE1\u606F\u4FDD\u5B58"))),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    React.createElement("p", { className: "userInfo step-desc" }, "\u7528\u6237\u4FE1\u606F\u4FDD\u5BC6"))),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    React.createElement("p", { className: "electric step-desc" }, "\u7535\u5B50\u8BA4\u8BC1\u3001\u7535\u5B50\u7B7E\u540D"))),
                            React.createElement("div", { className: "line" })),
                        React.createElement("li", { className: "block last" },
                            React.createElement("div", { className: "step" },
                                React.createElement("i", { className: "iconfont icon-duihao1" }),
                                React.createElement("div", { className: "step-desc" },
                                    React.createElement("div", { className: "receipt step-desc" },
                                        "\u7F51\u7EDC\u501F\u8D37\u4E2D\u4ECB\u673A\u6784\u4FE1\u606F",
                                        React.createElement("br", null),
                                        "\u5B89\u5168\u7B49\u7EA7\u4FDD\u62A4\u5BA1\u6838\u56DE\u6267")))))),
                React.createElement("li", { className: "security big-block" },
                    React.createElement("p", { className: "title" }, "\u4FE1\u606F\u5B89\u5168\u6D4B\u8BC4\u8BA4\u8BC1\u4FE1\u606F"),
                    React.createElement("p", { className: "text" }, "\u516C\u5B89\u673A\u5173\u6838\u53D1\u7684\u7F51\u7AD9\u5907\u6848\u56FE\u6807\u53CA\u7F16\u53F7\uFF1A\u5907\u6848\u5B8C\u6210\u540E\u62AB\u9732")))));
    };
    return Onrecord_PC;
}(React.Component));
export default Onrecord_PC;
//# sourceMappingURL=main-pc.js.map