import React from "react";
var Contact = function (prop) {
    return (React.createElement("div", { className: "footer-contact" },
        React.createElement("div", { className: "contact-type" },
            React.createElement("div", { className: "title" }, "\u5173\u6CE8\u6211\u4EEC"),
            React.createElement("ul", { className: "contact-list" },
                React.createElement("li", { className: "wechat" },
                    React.createElement("div", { className: "logo l-1" },
                        React.createElement("i", { className: "iconfont icon-weixin" })),
                    React.createElement("div", { className: "pop-box pop-qr" },
                        React.createElement("div", { className: "box-qr" }),
                        React.createElement("p", { className: "follow" }, "\u5173\u6CE8\u91D1\u94F6\u732B\u5FAE\u4FE1")),
                    React.createElement("p", { className: "text" }, "\u5FAE\u4FE1\u516C\u4F17\u53F7")),
                React.createElement("li", { className: "sina" },
                    React.createElement("a", { href: "http://weibo.com/u/3822187413" },
                        React.createElement("div", { className: "logo l-2" },
                            React.createElement("i", { className: "iconfont icon-xinlang" })),
                        React.createElement("p", { className: "text" }, "\u65B0\u6D6A\u5FAE\u535A"))),
                React.createElement("li", { className: "qq" },
                    React.createElement("div", { className: "logo l-3" },
                        React.createElement("i", { className: "iconfont icon-qq" })),
                    React.createElement("div", { className: "pop-box pop-qq" },
                        React.createElement("p", { className: "qq-info" }, "\u5B98\u65B9\u4EA4\u6D411\u7FA4"),
                        React.createElement("p", { className: "qq-info" },
                            "QQ\uFF1A",
                            React.createElement("span", null, "368910758"),
                            "(\u6EE1)"),
                        React.createElement("p", { className: "qq-info" }, "\u5B98\u65B9\u4EA4\u6D412\u7FA4"),
                        React.createElement("p", { className: "qq-info last" },
                            "QQ\uFF1A",
                            React.createElement("span", null, "271865771"))),
                    React.createElement("p", { className: "text" }, "\u5B98\u65B9\u4EA4\u6D41\u7FA4")))),
        React.createElement("div", { className: "contact-qr" },
            React.createElement("div", { className: "title" }, "\u626B\u4E00\u626B \u9A6C\u4E0A\u53D8\u571F\u8C6A"),
            React.createElement("div", { className: "qr" },
                React.createElement("div", { className: "border-1 border" }),
                React.createElement("div", { className: "border-2 border" }),
                React.createElement("div", { className: "border-3 border" }),
                React.createElement("div", { className: "border-4 border" }),
                React.createElement("div", { className: "qr-perviewer" }))),
        React.createElement("div", { className: "contact-tele" },
            React.createElement("div", { className: "jym-logo" }),
            React.createElement("p", null, "\u5168\u56FD\u670D\u52A1\u70ED\u7EBF"),
            React.createElement("p", { className: "tele" },
                "4008-556-333 ",
                React.createElement("span", null, " \u6216")),
            React.createElement("p", { className: "tele" }, "021-38934666"),
            React.createElement("p", null, "\u5BA2\u670D\u5DE5\u4F5C\u65F6\u95F4\uFF1A9:00~18:00"))));
};
export default Contact;
//# sourceMappingURL=contact.js.map